name: Continues Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, ready_for_review, synchronize, labeled]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft != true || contains(github.event.pull_request.labels.*.name, 'run')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
